<?php

use Illuminate\Database\Seeder;

class CreativesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('creatives')->delete();
        
        \DB::table('creatives')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Donna Hensley',
                'title' => 'Voluptate voluptate',
                'description' => 'Autem dicta esse sed',
                'advertiser' => NULL,
                'link' => 'Aperiam sed necessit',
                'ad_image_size' => NULL,
                'type' => NULL,
                'image_path' => NULL,
                'video_path' => NULL,
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 1,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-02 07:52:30',
                'updated_at' => '2020-01-02 07:52:30',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Quintessa Norman',
                'title' => 'Sint quas cupiditate',
                'description' => 'Corporis blanditiis',
                'advertiser' => NULL,
                'link' => 'Maiores tenetur omni',
                'ad_image_size' => NULL,
                'type' => 'image_text',
                'image_path' => NULL,
                'video_path' => NULL,
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 2,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-02 08:07:20',
                'updated_at' => '2020-01-02 08:07:20',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Gemma Alston',
                'title' => 'Omnis voluptas tenet',
                'description' => 'Totam eius tempore',
                'advertiser' => NULL,
                'link' => 'Distinctio Tenetur',
                'ad_image_size' => NULL,
                'type' => 'image_button',
                'image_path' => 'C:\\wamp64\\tmp\\php5A4E.tmp',
                'video_path' => 'C:\\wamp64\\tmp\\php5A4E.tmp',
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 2,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-02 08:31:55',
                'updated_at' => '2020-01-02 08:31:55',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Yeo Patterson',
                'title' => 'Quia distinctio Fug',
                'description' => 'Assumenda sunt asper',
                'advertiser' => NULL,
                'link' => 'Quis fuga Nulla aut',
                'ad_image_size' => NULL,
                'type' => 'image',
                'image_path' => 'C:\\wamp64\\tmp\\php427E.tmp',
                'video_path' => 'C:\\wamp64\\tmp\\php427E.tmp',
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 2,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-02 08:32:55',
                'updated_at' => '2020-01-02 08:32:55',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Harriet Valencia',
                'title' => 'Et perspiciatis dol',
                'description' => 'Officiis aliqua Fug',
                'advertiser' => NULL,
                'link' => 'Dolor nobis maxime e',
                'ad_image_size' => NULL,
                'type' => 'image_text_button',
                'image_path' => 'files/images//kPwogplftKAJ1kLUhzOXTeqmHc2OLIOiEWfN33Ll.png',
                'video_path' => 'files/images//kPwogplftKAJ1kLUhzOXTeqmHc2OLIOiEWfN33Ll.png',
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 2,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-02 08:42:29',
                'updated_at' => '2020-01-02 08:42:29',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Armando Griffin',
                'title' => 'Sint aut aperiam qu',
                'description' => 'Doloremque et volupt',
                'advertiser' => NULL,
                'link' => 'Sit facere mollit si',
                'ad_image_size' => NULL,
                'type' => 'image_text',
                'image_path' => 'files/images/AtB1VbdBuSGBQ9Ts57aKaqxGCmTo7px7g3AS9lXp.png',
                'video_path' => 'files/images/AtB1VbdBuSGBQ9Ts57aKaqxGCmTo7px7g3AS9lXp.png',
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 2,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-02 08:43:47',
                'updated_at' => '2020-01-02 08:43:47',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Amelia Perry',
                'title' => 'Culpa possimus aute',
                'description' => 'Ab est in voluptas',
                'advertiser' => '',
                'link' => 'Vero qui eligendi es',
                'ad_image_size' => NULL,
                'type' => 'image_text_button',
                'image_path' => 'files/images/OmcFSNrelOjouRD8CH6jclqJiBxSBMagO65xp83D.png',
                'video_path' => 'files/images/OmcFSNrelOjouRD8CH6jclqJiBxSBMagO65xp83D.png',
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 2,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-02 08:56:44',
                'updated_at' => '2020-01-02 08:56:44',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'India Best',
                'title' => 'Eum aliquam enim par',
                'description' => 'Architecto sint libe',
                'advertiser' => '',
                'link' => 'Tempore corporis ul',
                'ad_image_size' => NULL,
                'type' => 'image_text_button',
                'image_path' => 'files/images/w7GBQJ3pAa0mDNdO6hUXueTRwKya5AHBAHmJ64go.png',
                'video_path' => '',
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 2,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-02 09:00:02',
                'updated_at' => '2020-01-02 09:00:02',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Martena Norman',
                'title' => 'Ea rerum laborum eiu',
                'description' => 'Dolore qui mollit vo',
                'advertiser' => NULL,
                'link' => 'https://www.moh.org',
                'ad_image_size' => NULL,
                'type' => 'image_button',
                'image_path' => 'files/images/TV2ZC5ejuSrhS8wcljMdNzVzITXvO3Tr6ApvjnlF.png',
                'video_path' => NULL,
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 4,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-08 06:49:52',
                'updated_at' => '2020-01-08 06:49:52',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Brent Benton',
                'title' => 'Voluptatem sit aliq',
                'description' => 'Eum similique tempor',
                'advertiser' => NULL,
                'link' => 'https://www.lysuzasajot.cm',
                'ad_image_size' => NULL,
                'type' => NULL,
                'image_path' => 'C:\\wamp64\\www\\airpushadmin\\public\\/files/',
                'video_path' => NULL,
                'video_link' => NULL,
                'status_id' => 5,
                'campaign_id' => 5,
                'impressions' => NULL,
                'clicks' => NULL,
                'devices' => NULL,
                'supports' => NULL,
                'ctr' => NULL,
                'average_bid' => NULL,
                'vid_type' => NULL,
                'spend' => NULL,
                'conversion' => NULL,
                'conversion_rate' => NULL,
                'CPA' => NULL,
                'created_at' => '2020-01-08 07:34:05',
                'updated_at' => '2020-01-08 07:34:05',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}